services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=gpt-4
      - BACKEND_URL=http://backend:3001
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBEDDING_FUNCTION=text-embedding-3-small
    volumes:
      - chroma_db:/app/chroma.db
    restart: unless-stopped

volumes:
  chroma_db: